# Generated by Django 4.1.7 on 2023-03-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_new',
        ),
    ]
