# Generated by Django 4.1.7 on 2023-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_band_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='record',
            field=models.BooleanField(default=False),
        ),
    ]
