# Generated by Django 4.1.7 on 2023-03-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='record',
        ),
    ]
